### ISSUE TITLE
Disappearing System Indicator

### ISSUE THREAD

**Issue by knorquist** [elementary/wingpanel-indicator-nightlight#40]
The indicator sometimes disappears. I can still access settings by clicking on where it should be, as shown in the screenshot. I'm currently still experiencing a similar issue with the bluetooth indicator as well, which you can see in the screenshot too.

![screenshot from 2018-11-23 23-47-07](https://user-images.githubusercontent.com/3306524/48965875-9171c100-ef7a-11e8-9274-e4c93b5be498.png)

**Comment by peteruithoven** [comment]
Probably related to: https://github.com/elementary/wingpanel-indicator-bluetooth/issues/64

**Comment by peteruithoven** [comment]
This has been fixed with: https://github.com/elementary/wingpanel/pull/187

**Comment by stsdc** [comment]
Still have this issue. Indicator disappeared after sleep. `killall wingpanel` did not work.
![obraz](https://user-images.githubusercontent.com/6031763/59966047-cb0da900-9516-11e9-959b-b5ec59fbbad9.png)

Nothing also changes when I try enable/disable Night Light from Settings. It does not react. 

```
System:    Host: desktop Kernel: 5.1.12-050112-generic x86_64 bits: 64 Desktop: Gnome
           Distro: elementary OS 5.0 Juno
Machine:   Device: desktop Mobo: ASRock model: B450 Gaming-ITX/ac serial: N/A UEFI: American Megatrends v: P3.30 date: 05/17/2019
CPU:       Quad core AMD Ryzen 5 2400G with Radeon Vega Graphics (-MT-MCP-) speed/max: 1534/3600 MHz
Graphics:  Card: Advanced Micro Devices [AMD/ATI] Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series]
           Display Server: x11 (X.Org 1.19.6 ) drivers: ati,amdgpu (unloaded: modesetting,fbdev,vesa,radeon)
           Resolution: 1920x1080@60.00hz
           OpenGL: renderer: AMD RAVEN (DRM 3.30.0, 5.1.12-050112-generic, LLVM 8.0.0)
           version: 4.5 Mesa 19.1.0 - padoka PPA
Network:   Card-1: Intel Dual Band Wireless-AC 3168NGW [Stone Peak] driver: iwlwifi
           Card-2: Intel I211 Gigabit Network Connection driver: igb
Drives:    HDD Total Size: 1628.3GB (5.0% used)
Info:      Processes: 289 Uptime: 1 day Memory: 2333.5/5946.4MB Client: Shell (zsh) inxi: 2.3.56
```

**Comment by peteruithoven** [comment]
@stsdc Thanks for all the info. Just to rule out one more thing, you currently within the time period where nightlight is active? Otherwise the indicator is hidden. You can try altering the schedule manually to test this.

**Comment by peteruithoven** [comment]
@stsdc Also, can you also click on the area where the indicator should be?

**Comment by stsdc** [comment]
@peteruithoven ok, my fault did not know that it autohides when out of time period. Looks like that is a different issue then.
